export type supportedLanguages =
  | 'en-IN'
  | 'en-US'
  | 'en-UK'
  | 'hi-IN'
  | 'ur-IN'
  | 'ar-EG'
  | 'tr-TR';

export type variations =
  | 'normal'
  | 'grammar-corrector'
  | 'doctor'
  | 'web-design-consultant'
  | 'poet'
  | 'rapper'
  | 'math-teacher'
  | 'historian'
  | 'chef'
  | 'makeup-artist'
  | 'data-scientist'
  | 'advertiser'
  | 'legal-advisor'
  | 'it-expert'
  | 'technical-writer'
  | 'regex-generator'
  | 'social-media-influencer'
  | 'gavin-belson'
  | 'russ-hanneman'
  | 'munna'
  | 'prompt_generator';
